// export const CategoryConstants = {
//     SUB_CATEGORY_REQUEST: 'SUB_CATEGORY_REQUEST',
//     SUB_CATEGORY_SUCCESS: 'SUB_CATEGORY_SUCCESS',
//     SUB_CATEGORY_FAILURE: 'SUB_CATEGORY_FAILURE',
// };
